//#define MAINBG_WIDTH  800
//#define MAINBG_HEIGHT  595
//

//播放控制
#define  MU_PALY 0
#define  MU_SETPOSITION 1
#define  MU_CLOSE 2
#define  MU_MIN 3
#define  MU_VOLUME 4
#define  MU_ADD 5
#define  MU_SETVOLPOSITION 6
#define	 MU_MUSICLIST 7



//自定义消息

//定义歌曲进度条移动
#define WM_MYMOVE_MESSAGE  (WM_USER+100)
//定义系统托盘
#define WM_MYCLOSEWINDOW_MESSAGE (WM_USER+101)

//软件设置
#define  IDR_MYSETTING_MESSAGE  1
//打开官方
#define  IDR_MYWEBSITE_MESSAGE 2
#define  IDR_MYCLOSE_MESSAGE 3


#define WM_LAYERPAINT_MESSAGE  (WM_USER+200)
#define WM_MYREFERENCE_MESSAGE  (WM_USER+201)

#define  WM_MYMUSICNAME_MESSAGE  (WM_USER+202)

#define WM_MYMUSICTIMES_MESSAGE (WM_USER+203)
#define WM_MYMUSICVOL_MESSAGE (WM_USER+204)
#define WM_MYMUSICPLAY_MESSAGE (WM_USER+205)
#define WM_ONSETBGALPHA_MESSAGE (WM_USER+206)
#define WM_STARTRUNOPENFILE_MESSAGE (WM_USER+207)
#define WM_SETMUSIC3D_MESSAGE (WM_USER+208)
#define WM_ACTIVATE_MESSAGE (WM_USER+209)
#define WM_ONSETBGIMG_MESSAGE (WM_USER+210)



#define  MUSIC_EQ(A,B) BASS_DX8_PARAMEQ p;p.fGain=A;p.fBandwidth=12;p.fCenter=B;